<style>
    @keyframes textAnimation10 {
        0% { color: #FFA500; } /* Orange */
        50% { color: #FF6347; } /* Tomato */
        100% { color: #FF7F50; } /* Coral */
    }
</style>

<div style="border: 4px solid #FFA500; border-radius: 45px; padding: 45px; box-shadow: 0 9px 18px rgba(0, 0, 0, 0.7); background: linear-gradient(45deg, #FFFFFF, #FFDAB9); max-width: 750px; margin: 50px auto;">
    <p style="font-family: 'Garamond', serif; font-size: 55px; text-align: center; color: #FFA500; font-style: italic; font-weight: bold; animation: textAnimation10 9s infinite alternate;">Video Game Sales Exploratory Data Analysis</p>
</div>

![](https://media1.tenor.com/m/nqbZejon51sAAAAC/video-games-tom-ellis.gif)

<div style='background-color: #f0f0f0; color: #333; border: 2px solid #ccc; border-radius: 5px; padding: 15px;'>

# <span style='color:#E1B12D;'>Meta Data</span><br>

<i>This dataset comprises a collection of video games with sales exceeding 100,000 copies. It was obtained through scraping <a href="https://www.vgchartz.com/"><b>vgchartz.com</b></a>.</i><br>

<b>Fields include</b><br>

   -  <b>Name</b> - The game's title<br>
   -  <b>Platform</b> - The platform of the game's release (e.g., PC, PS4)<br>
   - <b>Year</b> - The year of the game's release<br>
   - <b>Genre</b> - The genre of the game<br>
   - <b>Publisher</b> - The game's publisher<br>
   - <b>NA_Sales</b> - Sales in North America (in millions)<br>
   - <b>EU_Sales</b> - Sales in Europe (in millions)<br>
   - <b>JP_Sales</b> - Sales in Japan (in millions)<br>
   - <b>Other_Sales</b> - Sales in the rest of the world (in millions)<br>
   - <b>Global_Sales</b> - Total worldwide sales<br>

<i>The script used to scrape the data is available at <a href="https://github.com/GregorUT/vgchartzScrape">GitHub</a>. It is based on BeautifulSoup using Python. There are 16,598 records. Two records were dropped due to incomplete information.</i><br>

# <span style='color:#E1B12D;'>Objective</span><br>

<i>Data analysis can be categorized into two fields: Hypothesis Generation and Hypothesis Confirmation (also called confirmatory

----

<div style="border: 3px solid orange; border-radius: 20px; padding: 10px; width: fit-content;">
    <div style="background: linear-gradient(45deg, #FFFFFF, #FFDAB9); border-radius: 20px; padding: 30px; font-family: Arial, sans-serif; font-size: 28px; color: #FFA500; display: inline-block; text-align: center; box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);">
        <span style="font-weight: bold; margin-right: 10px;">1</span>
        <span style="color: #FF6347; margin-right: 10px; font-size: 42px;">🌠</span>
        <span style="font-style: roboto; font-weight: bold;">Import Packages</span>
    </div>
</div>

In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
from tabulate import tabulate

<div style="border: 3px solid orange; border-radius: 20px; padding: 10px; width: fit-content;">
    <div style="background: linear-gradient(45deg, #FFFFFF, #FFDAB9); border-radius: 20px; padding: 30px; font-family: Arial, sans-serif; font-size: 28px; color: #FFA500; display: inline-block; text-align: center; box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);">
        <span style="font-weight: bold; margin-right: 10px;">2</span>
        <span style="color: #FF6347; margin-right: 10px; font-size: 42px;">🌠</span>
        <span style="font-style: roboto; font-weight: bold;">Import Dataset</span>
    </div>
</div>

In [3]:
df = pd.read_csv('/kaggle/input/global-video-game-sales/vgsales.csv')

In [4]:
def display_df_info(df):
    # Display shape
    rows, cols = df.shape
    print(f"╔{'═'*30}╗")
    print(f"║{'DataFrame Shape':^30}║")
    print(f"╠{'═'*30}╣")
    print(f"║{'Rows:':<10}{rows:>10}          ║")
    print(f"║{'Columns:':<10}{cols:>10}          ║")
    print(f"╚{'═'*30}╝")


    # Display data types
    print(f"\n╔{'═'*30}╗")
    print(f"║{'DataFrame Column Data Types':^30}║")
    print(f"╠{'═'*30}╣")
    for col, dtype in df.dtypes.items():
        print(f"║{col:<20}{str(dtype):>10}║")
    print(f"╚{'═'*30}╝")

# Example usage
display_df_info(df)

╔══════════════════════════════╗
║       DataFrame Shape        ║
╠══════════════════════════════╣
║Rows:          16598          ║
║Columns:          11          ║
╚══════════════════════════════╝

╔══════════════════════════════╗
║ DataFrame Column Data Types  ║
╠══════════════════════════════╣
║Rank                     int64║
║Name                    object║
║Platform                object║
║Year                   float64║
║Genre                   object║
║Publisher               object║
║NA_Sales               float64║
║EU_Sales               float64║
║JP_Sales               float64║
║Other_Sales            float64║
║Global_Sales           float64║
╚══════════════════════════════╝

In [5]:
df.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;">2.1 || Dealing with Missing values</div>

---

In [6]:
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64


> <div style="color: orange; font-weight: bold; font-size: larger;">We got Missing Values In Year and Publisher Column</div>

<div style="color: orange; margin-top: 10px;"><b>How I will deal with these Missing Values</b></div>

<div style="color: orange; margin-top: 10px;">Publisher</div>
<ul>
    <li><span style="color: orange;">Strategy:</span> I simply replace NaN (Null Values) with a string ('Unknown') instead of removing that column because I am doing EDA and it will provide some information.</li>
</ul>

<div style="color: orange; margin-top: 10px;">Year</div>
<ul>
    <li><span style="color: orange;">Strategy:</span> I simply Use Digit 0000 to deal with Null values because there are 271 null values. In this way, I will not lose actual information and provide insights from the real dataset without changing anything out of it.</li>
</ul>

In [7]:
# Or use the alternative suggested by the warning
df['Publisher'] = df['Publisher'].fillna('Unknown')

In [8]:
# df['Year'].fillna(0000, inplace=True)
df['Year'] = df['Year'].fillna(0)

In [12]:
# it is compulsory to change the data type because we got some unusual values like this ===> 2002.0 2023.0 to ===> 2002 , 2023 
df['Year'] = df['Year'].astype(int)

In [13]:
df.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64


> <div style="color: orange; font-weight: bold; font-size: larger;">Successfully deal with Missing Values </div>


---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;">2.2 ||  Checking and dealing With Wrong Data Type </div>

---

In [11]:
df.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

In [12]:
df.dtypes

Rank              int64
Name             object
Platform         object
Year              int64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object


---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;">2.3 ||  Dealing With Column [Name]</div>

---

In [13]:
df['Name'].unique

<bound method Series.unique of 0                                              Wii Sports
1                                       Super Mario Bros.
2                                          Mario Kart Wii
3                                       Wii Sports Resort
4                                Pokemon Red/Pokemon Blue
                               ...
16593                  Woody Woodpecker in Crazy Castle 5
16594                       Men in Black II: Alien Escape
16595    SCORE International Baja 1000: The Official Game
16596                                          Know How 2
16597                                    Spirits & Spells
Name: Name, Length: 16598, dtype: object>

In [14]:
#  There is a number of games having their version like Taken 3 , Taken 7 so if i remove digits from it then i will lost information so i have tried this simple but effective way to deal with this 
#  problem in this way i will not lost any information plus point is i would be able to keep it in correct datatype :)  
df['Name'] = df['Name'].str.replace('5', 'Five')
df['Name'] = df['Name'].str.replace('9', 'Nine')
df['Name'] = df['Name'].str.replace('8', 'Eight')
df['Name'] = df['Name'].str.replace('3', 'Three')
df['Name'] = df['Name'].str.replace('2', 'Two')
df['Name'] = df['Name'].str.replace('7', 'Seven')
df['Name'] = df['Name'].str.replace('6', 'Six')
df['Name'] = df['Name'].str.replace('4', 'Four')
df['Name'] = df['Name'].str.replace('1', 'One')
df['Name'] = df['Name'].str.replace('0', 'Zero')

In [15]:
# Example: Remove non-alphanumeric characters from the 'Name' column 
df['Name'] = df['Name'].replace('[^a-zA-Z0-9\s]', '', regex=True)

In [16]:
# Example: Remove numeric characters from the 'Name' column
df['Name'] = df['Name'].replace('\d', '', regex=True)

In [17]:
# Example: Display unique values in the 'Name' column
df['Name']

0                                               Wii Sports
1                                         Super Mario Bros
2                                           Mario Kart Wii
3                                        Wii Sports Resort
4                                  Pokemon RedPokemon Blue
                               ...
16593                Woody Woodpecker in Crazy Castle Five
16594                         Men in Black II Alien Escape
16595    SCORE International Baja OneZeroZeroZero The O...
16596                                         Know How Two
16597                                      Spirits  Spells
Name: Name, Length: 16598, dtype: object

In [18]:
df['Name'] = df['Name'].str.strip()

In [19]:
df.dtypes

Rank              int64
Name             object
Platform         object
Year              int64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [20]:
#  printing all unique values to manually check the data from a human eye with eagle eyesight abilities 
unique_names = df['Name'].unique()

# Display unique values using a loop
for name in unique_names:
    print(name)

Wii Sports

Super Mario Bros

Mario Kart Wii

Wii Sports Resort

Pokemon RedPokemon Blue

Tetris

New Super Mario Bros

Wii Play

New Super Mario Bros Wii

Duck Hunt

Nintendogs

Mario Kart DS

Pokemon GoldPokemon Silver

Wii Fit

Wii Fit Plus

Kinect Adventures

Grand Theft Auto V

Grand Theft Auto San Andreas

Super Mario World

Brain Age Train Your Brain in Minutes a Day

Pokemon DiamondPokemon Pearl

Super Mario Land

Super Mario Bros Three

Grand Theft Auto Vice City

Pokemon RubyPokemon Sapphire

Pokemon BlackPokemon White

Brain Age Two More Training in Minutes a Day

Gran Turismo Three ASpec

Call of Duty Modern Warfare Three

Pokmon Yellow Special Pikachu Edition

Call of Duty Black Ops

Pokemon XPokemon Y

Call of Duty Black Ops Three

Call of Duty Black Ops II

Call of Duty Modern Warfare Two

Grand Theft Auto III

Super Smash Bros Brawl

Animal Crossing Wild World

Mario Kart Seven

Halo Three

Pokemon HeartGoldPokemon SoulSilver

Super Mario SixFour

Gran Turismo Four

Super Mario Galaxy

Pokemon Omega RubyPokemon Alpha Sapphire

Super Mario Land Two Six Golden Coins

Grand Theft Auto IV

Gran Turismo

Super Mario ThreeD Land

Gran Turismo Five

Super Mario AllStars

Pokemon FireRedPokemon LeafGreen

Just Dance Three

Call of Duty Ghosts

Halo Reach

Mario Kart SixFour

New Super Mario Bros Two

Halo Four

Final Fantasy VII

Just Dance Two

Gran Turismo Two

Call of Duty Four Modern Warfare

Donkey Kong Country

Minecraft

Animal Crossing New Leaf

Mario Party DS

The Elder Scrolls V Skyrim

Super Mario Kart

FIFA OneSix

Wii Party

Halo Two

Mario Party Eight

Pokemon Black TwoPokemon White Two

FIFA Soccer OneThree

The Sims Three

GoldenEye ZeroZeroSeven

Mario  Sonic at the Olympic Games

Final Fantasy X

Final Fantasy VIII

Pokmon Platinum Version

PacMan

Grand Theft Auto Liberty City Stories

Super Mario Galaxy Two

Star Wars Battlefront TwoZeroOneFive

Call of Duty Advanced Warfare

The Legend of Zelda Ocarina of Time

Crash Bandicoot Two Cortex Strikes Back

Super Mario Bros Two

Super Smash Bros for Wii U and ThreeDS

Call of Duty World at War

Battlefield Three

The Legend of Zelda Twilight Princess

Just Dance

Need for Speed Underground

Tekken Three

Crash Bandicoot Three Warped

Super Smash Bros Melee

Mario Kart Eight

Fallout Four

Mario Kart Double Dash

Just Dance Four

FIFA OneFour

Need for Speed Underground Two

Medal of Honor Frontline

Uncharted Three Drakes Deception

Crash Bandicoot

Zumba Fitness

Gears of War Two

Uncharted Two Among Thieves

FIFA OneTwo

Big Brain Academy

Red Dead Redemption

FIFA OneFive

Donkey Kong Country Returns

The Legend of Zelda

Assassins Creed III

Halo Combat Evolved

Pokmon Emerald Version

Kingdom Hearts

Pokmon Crystal Version

Halo Three ODST

Super Mario Sunshine

Street Fighter II The World Warrior

World of Warcraft

Driver

Kinect Sports

Gears of War Three

Gears of War

Metal Gear Solid Two Sons of Liberty

Sonic the Hedgehog Two

Metal Gear Solid Four Guns of the Patriots

Metal Gear Solid

The Last of Us

Final Fantasy XII

LittleBigPlanet

Dragon Quest IX Sentinels of the Starry Skies

LEGO Star Wars The Complete Saga

Resident Evil Two

Tekken Two

Cooking Mama

Destiny

Assassins Creed II

Super Smash Bros

Assassins Creed

Batman Arkham City

Forza Motorsport Three

Monster Hunter Freedom Unite

Super Mario Advance

Mario Kart Super Circuit

Pokemon Stadium

Crash Bandicoot The Wrath of Cortex

Final Fantasy XIII

Dr Mario

Pokemon Pinball

Final Fantasy IX

Final Fantasy XTwo

Donkey Kong SixFour

Professor Layton and the Curious Village

Tomb Raider II

Madden NFL TwoZeroZeroFour

Dragon Quest VIII Journey of the Cursed King

Diablo III

New Super Mario Bros U

Super Mario Land Three Wario Land

The Legend of Zelda Phantom Hourglass

Donkey Kong Country Two Diddys Kong Quest

Tomodachi Life

Medal of Honor Rising Sun

Kirbys Dream Land

Fable III

Microsoft Flight Simulator

Guitar Hero II

Resident Evil Five

Grand Theft Auto Vice City Stories

FIFA Soccer OneOne

Resident Evil

Tony Hawks Pro Skater

Warzone TwoOneZeroZero

Spyro the Dragon

Links Crossbow Training

Guitar Hero III Legends of Rock

Fallout Three

Pokemon Mystery Dungeon Explorers of TimeExplorers of Darkness

Uncharted Drakes Fortune

Madden NFL ZeroSix

Diddy Kong Racing

Monster Hunter Freedom Three

God of War III

StarCraft II Wings of Liberty

Crash Team Racing

FIFA OneSeven

Driver Two

The Simpsons Hit  Run

Tony Hawks Pro Skater Two

Animal Crossing City Folk

The Lord of the Rings The Two Towers

Forza Motorsport Four

Tomb Raider

The Legend of Zelda A Link to the Past

The Legend of Zelda The Wind Waker

Mario  Sonic at the Olympic Winter Games

Luigis Mansion Dark Moon

Splatoon

Madden NFL TwoZeroZeroFive

Pitfall

Madden NFL ZeroSeven

SpiderMan The Movie

Dragon Quest VII Warriors of Eden

Uncharted The Nathan Drake Collection

God of War

Nintendo Land

Michael Jackson The Experience

Tony Hawks Pro Skater Three

Winning Eleven Pro Evolution Soccer TwoZeroZeroSeven

The Elder Scrolls IV Oblivion

Zelda II The Adventure of Link

Need for Speed Most Wanted

Resistance Fall of Man

Sonic the Hedgehog

Kingdom Hearts II

Asteroids

Fable II

Halo Five Guardians

Super Mario ThreeD World

Batman Arkham Asylum

Assassins Creed Revelations

Namco Museum

Metal Gear Solid Three Snake Eater

Daxter

Warcraft II Tides of Darkness

FIFA Soccer ZeroSix

EyeToy Play

Uncharted Four A Thiefs End

Gran Turismo Five Prologue

Street Fighter IV

Teenage Mutant Ninja Turtles

Excitebike

Frogger

Madden NFL TwoZeroZeroThree

Watch Dogs

HalfLife

Super Mario World Two Yoshis Island

FIFA Soccer ZeroSeven

The Legend of Zelda Skyward Sword

Street Fighter II Turbo

Carnival Games

World of Warcraft The Burning Crusade

Fallout New Vegas

God of War II

Forza Motorsport Two

World Soccer Winning Eleven Nine

Namco Museum VolThree

Tekken Tag Tournament

Far Cry Four

Star Fox SixFour

Golf

Professor Layton and the Diabolical Box

Left Four Dead Two

Namco Museum FiveZeroth Anniversary

EA Sports Active

Assassins Creed Unity

Donkey Kong Land

Tony Hawks Underground

Assassins Creed IV Black Flag

Monster Hunter Four Ultimate

MotorStorm

Tekken Five

Dragon Warrior III

Sports Champions

NBA TwoKOneSix

World Soccer Winning Eleven Eight International

Flash Focus Vision Training in Minutes a Day

Namco Museum VolOne

The Legend of Zelda Links Awakening

Mario  Luigi Bowsers Inside Story

Big Brain Academy Wii Degree

Nintendogs  cats

Batman Arkham Knight

Mario  Sonic at the London TwoZeroOneTwo Olympic Games

LEGO Indiana Jones The Original Adventures

Resident Evil Directors Cut

Ratchet  Clank Size Matters

Just Dance TwoZeroOneFour

The Sims Unleashed

Super Paper Mario

Harry Potter and the Sorcerers Stone

The Witcher Three Wild Hunt

Resident Evil Three Nemesis

Spyro Year of the Dragon

FIFA Soccer TwoZeroZeroFive

Pokmon Trading Card Game

Battlefield Four

MySims

Friend Collection

Tony Hawks Pro Skater Four

Midnight Club Three DUB Edition

BanjoKazooie

SOCOM US Navy SEALs

Guitar Hero World Tour

Gran Turismo Six

Jak and Daxter The Precursor Legacy

Pokemon Snap

FIFA Soccer OneZero

Pro Evolution Soccer TwoZeroZeroEight

Resident Evil Four

Tom Clancys The Division

Star Wars Battlefront

Doom II Hell on Earth

The Simpsons Road Rage

Cooking Mama Two Dinner With Friends

Luigis Mansion

Star Wars Battlefront II

WWF SmackDown

Croc Legend of the Gobbos

The Getaway

Tomb Raider III Adventures of Lara Croft

James Bond ZeroZeroSeven Agent Under Fire

LEGO Star Wars The Video Game

Rugrats in Paris The Movie

Spyro Two Riptos Rage

Left Four Dead

Donkey Kong Country Three Dixie Kongs Double Trouble

Assassins Creed Brotherhood

Kung Fu

Clubhouse Games

FIFA Soccer TwoZeroZeroFour

Battlefield Bad Company Two

Guitar Hero On Tour

Far Cry Three

Monster Hunter Four

Borderlands

Tekken Four

LittleBigPlanet Two

Grand Theft Auto Two

Final Fantasy III

SpiderMan Two

FOne Race

FIFA Soccer TwoZeroZeroThree

Crash Bash

LEGO Batman The Videogame

Metal Gear Solid V The Phantom Pain

The Legend of Zelda Spirit Tracks

WWF War Zone

The Legend of Zelda Majoras Mask

Professor Layton and the Unwound Future

Rugrats Search For Reptar

English Training Have Fun Improving Your Skills

James Bond ZeroZeroSeven Nightfire

Ratchet  Clank

Mario Party Nine

Star Wars Episode III Revenge of the Sith

Max Payne

The Lord of the Rings The Return of the King

Assassins Creed Syndicate

True Crime Streets of LA

Wii Music

Gran Turismo PSP

Monster Hunter X

Tekken

LA Noire

Madden NFL OneSix

Yokai Watch Two GansoHonke

ZeroZeroSeven Tomorrow Never Dies

Baseball

Killer Instinct

WWF SmackDown Two Know Your Role

Crisis Core Final Fantasy VII

God of War Chains of Olympus

Dragon Quest VI Maboroshi no Daichi

Dance Central

Enter the Matrix

Super Mario Maker

Rhythm Heaven

Ace Combat ZeroFour Shattered Skies

Club Penguin Elite Penguin Force

Animal Crossing

Sonic Rush

Resident Evil Six

Halo The Master Chief Collection

FIFA Soccer ZeroEight

SpiderMan

Need for Speed III Hot Pursuit

Star Wars Episode I Racer

Personal Trainer Cooking

Dragon Warrior IV

Heavy Rain

Mass Effect Two

Dragon Ball Z Budokai

Madden NFL TwoZeroZeroTwo

World Class Track Meet

Borderlands Two

The Legend of Zelda A Link Between Worlds

Donkey Kong

The Sims Vacation

Mass Effect Three

Kung Fu Panda

Epic Mickey

Saints Row Two

Rayman

Killzone Two

Tom Clancys Splinter Cell

Mike Tysons PunchOut

WWE SmackDown Shut Your Mouth

Gears of War Ultimate Edition

NBA TwoKOneThree

Dragon Ball Z Budokai Tenkaichi Three

wwe Smackdown vs Raw TwoZeroZeroSix

MiddleEarth Shadow of Mordor

Star Fox

The Sims Livin Large

World Soccer Winning Eleven Six International

Devil May Cry

Animal Crossing Happy Home Designer

The Sims Four

Star Wars The Old Republic

Sonic Heroes

Kirby Super Star Ultra

Hitman Two Silent Assassin

Wave Race SixFour

SOCOM II US Navy SEALs

WWE SmackDown vs RAW TwoZeroZeroSix

inFAMOUS

PacMan Collection

Mass Effect

WarioWare Smooth Moves

Cooking Mama Cook Off

Titanfall

Sonic Mega Collection Plus

Sega Superstars Tennis

World Soccer Winning Eleven Seven International

Hot Shots Golf Three

Call of Duty Finest Hour

Zumba Fitness Two

Syphon Filter

Imagine Babyz

Colin McRae Rally

Madden NFL OneThree

The Elder Scrolls III Morrowind

Mortal Kombat

FZero

Yoshis Story

Command  Conquer Red Alert

Skylanders Spyros Adventure

BioShock

Madden NFL OneZero

Medal of Honor

WWE SmackDown vs Raw

Metroid Prime

Finding Nemo

Myst

Need for Speed Hot Pursuit

Imagine Fashion Designer

WWE SmackDown Here Comes the Pain

Star Wars The Force Unleashed

Yoshis Island DS

Hot Shots Golf

Killzone Three

A Bugs Life

WWF SmackDown Just Bring It

Dragon Quest V Tenkuu no Hanayome

Mortal Kombat Trilogy

NBA Street

Professor Layton and the Last Specter

Monster Hunter Tri

Jak II

inFAMOUS Second Son

Ratchet  Clank Going Commando

Tekken Six

The Sims

Sonic and the Secret Rings

Saints Row The Third

Missile Command

Mario Paint

Pokmon Stadium Two

Metroid

Call of Duty Three

Onimusha Warlords

Mortal Kombat X

Mario Party

Madden NFL OneTwo

LEGO Star Wars II The Original Trilogy

Madden NFL OneOne

Mario vs Donkey Kong MiniLand Mayhem

Skate Three

Burnout Three Takedown

Yokai Watch Two Shinuchi

Need for Speed Shift

Final Fantasy XIIITwo

Call Of Duty Two Big Red One

Fable

Hannah Montana

Skylanders Giants

Medal of Honor Heroes

Super Mario Bros The Lost Levels

Star Wars Shadows of the Empire

Midnight Club Street Racing

PacMan Adventures in Time

Halo Wars

God of War Collection

ESPN NFL TwoKFive

Mario Strikers Charged

NBA TwoKOneTwo

Style Savvy

Harry Potter and the Chamber of Secrets

Super Mario AllStars Limited Edition

Streets of Rage

FIFA Soccer ZeroNine

Ratchet  Clank Future Tools of Destruction

NBA Live TwoZeroZeroFive

Killzone Shadow Fall

Ghostbusters The Video Game DS Version

Monster Hunter Freedom Two

WWE SmackDown vs RAW TwoZeroZeroSeven

Ratchet  Clank Up Your Arsenal

Art Academy

Dragon Age Origins

Madden NFL ZeroEight

Sonic Adventure Two Battle

Dragon Warrior II

Pokmon Colosseum

Deca Sports

Madden NFL ZeroNine

Space Invaders

Crazy Taxi

Perfect Dark

Game Party

Dragon Warrior

Tomb Raider TwoZeroOneThree

Marvel Ultimate Alliance

PES TwoZeroZeroNine Pro Evolution Soccer

Mario Party Two

Rockstar Games Double Pack Grand Theft Auto III  Grand Theft Auto Vice City

LEGO Harry Potter Years OneFour

Mortal Kombat Deadly Alliance

Resistance Two

Pure

Tomb Raider The Last Revelation

Rock Band

NBA TwoKOneFour

Mario Party Four

uDraw Studio

Midnight Club Los Angeles

Final Fantasy V

Final Fantasy Tactics

Twisted Metal Two

Halo Combat Evolved Anniversary

Need for Speed Carbon Own the City

The Sims Bustin Out

Riven The Sequel to Myst

Tom Clancys Rainbow Six Vegas Two

Sonic Adventure

Ice Hockey

pro evolution soccer TwoZeroOneOne

Dragon Ball Z Budokai Two

ATV Offroad Fury

Dino Crisis

Need for Speed ProStreet

Tetris Plus

Pro Wrestling

Theme Hospital

Froggers Adventures Temple of the Frog

Need for Speed TwoZeroOneFive

Monopoly

Batman Arkham Origins

Dead Island

Guitar Hero

Kinect Disneyland Adventures

WCWnWo Revenge

Bloodborne

NBA TwoKOneFive

YuGiOh The Duelists of the Roses

HalfLife Two

The Incredibles

Tony Hawks Underground Two

Kinect Sports Season Two

Kirbys Dream Land Two

Donkey Kong Land II

Dragon Warrior Monsters

Skylanders SWAP Force

WWE SmackDown vs Raw TwoZeroZeroEight

My Fitness Coach

Resident Evil  Code Veronica X

The Legend of Zelda Majoras Mask ThreeD

Just Dance Kids

Mario Tennis

Grand Theft Auto

James Bond ZeroZeroSeven Everything or Nothing

WarioWare Touched

Need For Speed High Stakes

Chrono Trigger

Cool Boarders Three

LEGO Marvel Super Heroes

Guild Wars Two

Pokemon Ranger Shadows of Almia

God of War Ascension

Pro Evolution Soccer TwoZeroOneZero

Just Dance TwoZeroOneFive

Yokai Watch Busters

Mario Bros

TOCA Touring Car Championship

Paper Mario Sticker Star

Sonics Ultimate Genesis Collection

Super Monkey Ball Banana Blitz

Kirby Nightmare in Dream Land

Wario Land Four

Onimusha Two Samurais Destiny

Cool Boarders Two

Paper Mario The ThousandYear Door

Dissidia Final Fantasy

Sonic Advance

Spyro Season of Ice

Teenage Mutant Ninja Turtles II The Arcade Game

Dance Dance Revolution XTwo

New Super Luigi U

Prince of Persia The Sands of Time

Scribblenauts

The Legend of Zelda Links Awakening DX

BioShock Two

Devil May Cry Three Dantes Awakening Special Edition

Rock Band Two

Wario Land Three

Pro Yakyuu Family Stadium

Sonic Unleashed

High School Musical Makin the Cut

Pro Evolution Soccer TwoZeroOneTwo

Saints Row

Star Wars Knights of the Old Republic

Kirbys Pinball Land

Hitman Absolution

YuGiOh Duel Monsters Four

ATV Offroad Fury Two

Forza Motorsport Five

Madden NFL TwoFive

Pokemon Ranger

Mario  Luigi Superstar Saga

Star Wars Rogue Squadron

Tennis

The Sims House Party

Your Shape featuring Jenny McCarthy

Syphon Filter Two

Tom Clancys Rainbow Six Siege

Volleyball

Call of Duty Roads to Victory

Super Mario RPG Legend of the Seven Stars

Mahjong

RC ProAm

SimCity TwoZeroZeroZero

Demon Attack

Dance Dance Revolution Extreme

Tetris DS

Final Fantasy Tactics Advance

Far Cry Primal

Toy Story Three The Video Game

Kirbys Epic Yarn

Project Gotham Racing

Need for Speed Hot Pursuit Two

Mario Sports Mix

Dynasty Warriors Four

Parasite Eve

ScoobyDoo Night of OneZeroZero Frights

Project Gotham Racing JP weekly sales

Need for Speed Most Wanted FiveOneZero

Portal Two

Devil May Cry Three Dantes Awakening

Derby Stallion

Dead Rising

NBA TwoKOneOne

Wipeout The Game

The Sims Two Pets

Battlefield Hardline

Metal Gear Solid Peace Walker

World of Warcraft Cataclysm

Tetris Worlds

Need For Speed Undercover

Dance Dance Revolution Hottest Party

Mario Party Five

Sim Theme Park

Warcraft Orcs  Humans

Spec Ops Airborne Commando

Kingdom Hearts Birth by Sleep

UFC TwoZeroZeroNine Undisputed

Dark Souls

YuGiOh The Eternal Duelist Soul

Tom Clancys Splinter Cell Conviction

Pokemon Mystery Dungeon RedBlue Rescue Team

RFour Ridge Racer Type Four

SoulCalibur II

Mario  Luigi Dream Team

Pokmon Mystery Dungeon Blue Rescue Team

Sonic Mega Collection

NBA Jam

PGRFour  Project Gotham Racing Four

Kingdom Hearts ThreeFiveEightTwo Days

Dance Central Two

Rayman Raving Rabbids TV Party

SOCOM US Navy SEALs Combined Assault

Peter Jacksons King Kong The Official Game of the Movie

Need for Speed The Run

Madden NFL OneFive

OneZeroEightZero TenEighty Snowboarding

NBA Live TwoZeroZeroFour

Dead Space

Call of Duty Two

Forza Horizon

TouchMaster

Fire Emblem Awakening

DriveClub

Super Street Fighter II

Mortal Kombat vs DC Universe

Tenchu Stealth Assassins

SimCity

Dragon Age Inquisition

Sonic Classic Collection

Spyro Enter the Dragonfly

Devil May Cry Two

Burnout Paradise

ET The Extra Terrestrial

BioShock Infinite

Hot Shots Golf Open Tee

Rad Racer

Soccer

Kirby Squeak Squad

Tom Clancys Rainbow Six Vegas

Crash Nitro Kart

Star Wars Dark Forces

NBA Street Vol Two

Def Jam Vendetta

Who wants to be a millionaire

Scooby Doo and the Cyber Chase

Alleyway

Dragon Ball Z Budokai Three

Jet Moto Two

Tom Clancys Ghost Recon

XMen Legends

Mortal Kombat II

Virtua Fighter Two

Tetris DX

Mario Super Sluggers

The Legend of Zelda Oracle of Ages

Red Faction

The Sims Makin Magic

MX Unleashed

PaRappa The Rapper

Toy Story Mania

Mario Party Three

Game Party Two

Destiny The Taken King

LEGO Star Wars III The Clone Wars

Star Wars Rogue Leader Rogue Squadron II

Max Payne Three

Need for Speed Rivals

Yokai Watch

Ratchet  Clank Future A Crack in Time

YuGiOh Forbidden Memories

Mortal Kombat Deception

Hot Shots Golf Two

Medal of Honor European Assault All Region sales

WCW Nitro

High School Musical Sing It

Star Fox Adventures

FIFA TwoZeroZeroZero

Dynasty Warriors Three

The Legend of Zelda Oracle of Seasons

Shrek Two

The Legend of Dragoon

Turok Two Seeds of Evil

SingStar

LittleBigPlanet Three

NBA Live TwoZeroZeroTwo

Phineas and Ferb

Chrono Cross

GoldenEye ZeroZeroSeven TwoZeroOneZero

Mario Party Island Tour

Jak Three

Rayman Raving Rabbids Two

Kingdom Hearts Chain of Memories

Pinball

inFAMOUS Two

Gran Turismo Concept TwoZeroZeroOne Tokyo

Demons Souls

NCAA Football ZeroSix

Hey You Pikachu

Two Games in One Sonic Advance  ChuChu Rocket

World of Warcraft Mists of Pandaria

Jet Moto

Just Cause Three

Secret of Mana

The Orange Box

Air Combat

Kirby Triple Deluxe

Sonic  Knuckles

The Sims Hot Date

Metroid Prime Three Corruption

Dragon Quest VI Realms of Revelation

The Evil Within

DDRMAXTwo Dance Dance Revolution

Virtua Fighter Four

Sly Two Band of Thieves

Sonic Advance Two

NFL GameDay TwoZeroZeroZero

Disneys The Lion King

Beyond Two Souls

Kinect Star Wars

Midnight Club II

Dragon Quest Monsters Joker

SpongeBob SquarePants SuperSponge

The Getaway Black Monday

Professor Layton and the Mask of Miracle

Just Cause Two

Dragons Dogma

FiveZero Cent Bulletproof

Wii Party U

Final Fantasy II

Kirby SixFour The Crystal Shards

Dead or Alive Three

Metroid II Return of Samus

WWF Attitude

The SpongeBob SquarePants Movie

Golden Sun

Sonic the Hedgehog Three

Kid Icarus

Def Jam Fight for NY

State of Emergency

Two Games in One Double Pack The Incredibles  Finding Nemo The Continuing Adventures

The Urbz Sims in the City

Star Wars Starfighter

Madden NFL TwoZeroZeroZero

Pro Evolution Soccer

Crackdown

Yoshi

Disneys Aladdin

Kirbys Adventure

Cooking Mama Three Shop  Chop

Dance Dance Revolution X

Two Games in One Disney Princess  The Lion King

Star Wars Episode I The Phantom Menace

Xenosaga Episode I Der Wille zur Macht

The Beatles Rock Band

Forza Motorsport Six

Sonic Colors

Cruisn USA

Madden NFL NineNine

Uncharted Golden Abyss

SSX Tricky

Overwatch

Twisted Metal III


In [21]:
unique_names.shape

(11470,)

In [22]:
df['Name'].duplicated().sum()

5128

In [23]:
df.drop_duplicates(subset=['Name'], inplace=True)

In [24]:
df['Name'].duplicated().sum()

0



---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;">2.4 || Dealing With Column [Platform]</div>

---

In [25]:
df['Platform']

0        Wii
1        NES
2        Wii
3        Wii
4         GB
        ...
16589    PSV
16590    PSP
16592     DS
16593    GBA
16596     DS
Name: Platform, Length: 11470, dtype: object

In [26]:
df['Platform'] = df['Platform'].str.replace('3', 'Three')
df['Platform'] = df['Platform'].str.replace('2', 'Tow')
df['Platform'] = df['Platform'].str.replace('6', 'Six')
df['Platform'] = df['Platform'].str.replace('4', 'Four')
df['Platform'] = df['Platform'].str.replace('1', 'One')
df['Platform'] = df['Platform'].str.replace('0', 'Zero')

In [27]:
df['Platform'] = df['Platform'].replace('[^a-zA-Z0-9\s]', '', regex=True)

In [28]:
def display_value_counts(df, column_name):
    value_counts = df[column_name].value_counts()
    print(f"╔{'═'*30}╗")
    print(f"║{'Value Counts':^30}║")
    print(f"╠{'═'*30}╣")
    for index, count in value_counts.items():
        print(f"║{str(index):<20}{str(count):>10}║")
    print(f"╚{'═'*30}╝")

# Example usage
display_value_counts(df, 'Platform')

╔══════════════════════════════╗

║         Value Counts         ║

╠══════════════════════════════╣

║PSTow                     1855║

║DS                        1805║

║PS                        1121║

║Wii                        948║

║PSP                        904║

║PSThree                    705║

║GBA                        619║

║XThreeSixZero              559║

║PC                         495║

║ThreeDS                    396║

║PSV                        280║

║XB                         276║

║NSixFour                   245║

║PSFour                     241║

║SNES                       228║

║GC                         170║

║SAT                        148║

║TowSixZeroZero             125║

║NES                         89║

║GB                          84║

║WiiU                        55║

║DC                          43║

║XOne                        30║

║GEN                         23║

║NG                           9║

║SCD                          6║

║WS                           4║

║ThreeDO                      3║

║TGOneSix                     2║

║GG                           1║

║PCFX                         1║

╚══════════════════════════════╝

In [29]:
df['Platform'] = df['Platform'].astype('str')

### ***Dealing With Column [Genre]***

In [30]:
display_value_counts(df, 'Genre')

╔══════════════════════════════╗

║         Value Counts         ║

╠══════════════════════════════╣

║Action                    1917║

║Sports                    1375║

║Misc                      1327║

║Role-Playing              1218║

║Adventure                 1047║

║Shooter                    815║

║Racing                     766║

║Simulation                 725║

║Fighting                   612║

║Platform                   588║

║Strategy                   582║

║Puzzle                     498║

╚══════════════════════════════╝

In [31]:
df['Genre'] = df['Genre'].str.replace('-', ' ')

In [32]:
df['Genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)


---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;">2.5 || Dealing With Column [Publisher]</div>

---

In [33]:
df['Publisher'].unique()

array(['Nintendo', 'Microsoft Game Studios', 'Take-Two Interactive',
       'Sony Computer Entertainment', 'Activision', 'Ubisoft',
       'Bethesda Softworks', 'Electronic Arts', 'Sega', 'SquareSoft',
       'Atari', '505 Games', 'Capcom', 'GT Interactive',
       'Konami Digital Entertainment',
       'Sony Computer Entertainment Europe', 'Square Enix', 'LucasArts',
       'Virgin Interactive', 'Warner Bros. Interactive Entertainment',
       'Universal Interactive', 'Eidos Interactive', 'RedOctane',
       'Vivendi Games', 'Enix Corporation', 'Namco Bandai Games',
       'Palcom', 'Hasbro Interactive', 'THQ', 'Fox Interactive',
       'Acclaim Entertainment', 'MTV Games', 'Disney Interactive Studios',
       'Unknown', 'Majesco Entertainment', 'Codemasters', 'Red Orb',
       'Level 5', 'Midway Games', 'JVC', 'Deep Silver', '989 Studios',
       'NCSoft', 'UEP Systems', 'Maxis', 'Imagic', 'Tecmo Koei',
       'Valve Software', 'ASCII Entertainment', 'Mindscape', 'Infogrames',
       'Arena Entertainment', 'Square', 'Activision Value', 'Banpresto',
       'D3Publisher', 'Oxygen Interactive', 'Red Storm Entertainment',
       'Video System', 'Hello Games', 'Global Star', 'Gotham Games',
       'Westwood Studios', 'GungHo', 'Crave Entertainment', 'Hudson Soft',
       'Rising Star Games', 'Atlus', 'TDK Mediactive', 'ASC Games',
       'Accolade', 'Sony Online Entertainment', '3DO', 'RTL', 'Natsume',
       'Focus Home Interactive', 'Alchemist', 'Black Label Games',
       'SouthPeak Games', 'Mastertronic', 'Ocean',
       'Zoo Digital Publishing', 'Psygnosis', 'City Interactive',
       'Empire Interactive', 'Compile', 'Russel', 'Taito', 'Agetec',
       'GSP', 'Microprose', 'Play It', 'Slightly Mad Studios',
       'Tomy Corporation', 'Sammy Corporation', 'Koch Media',
       'Game Factory', 'Titus', 'Marvelous Entertainment', 'Genki',
       'Mojang', 'Pinnacle', 'CTO SpA', 'TalonSoft', 'Crystal Dynamics',
       'Quelle', 'mixi, Inc', 'Rage Software', 'Ubisoft Annecy',
       'Scholastic Inc.', 'Interplay', 'Mystique', 'ChunSoft',
       'Square EA', '20th Century Fox Video Games', 'Avanquest Software',
       'Hudson Entertainment', 'Nordic Games', 'Men-A-Vision', 'Nobilis',
       'SCi', 'Big Ben Interactive', 'Touchstone', 'Spike',
       'Jester Interactive', 'Nippon Ichi Software', 'LEGO Media',
       'Quest', 'Illusion Softworks', 'Tigervision', 'Funbox Media',
       'Rocket Company', 'Metro 3D', 'Mattel Interactive', 'IE Institute',
       'Rondomedia', 'Sony Computer Entertainment America',
       'Universal Gamex', 'Ghostlight', 'Wizard Video Games', 'Coleco',
       'BMG Interactive Entertainment', 'PQube', 'Trion Worlds', 'Laguna',
       'Ignition Entertainment', 'Takara', 'Kadokawa Shoten', 'Destineer',
       'Enterbrain', 'Xseed Games', 'Imagineer',
       'System 3 Arcade Software', 'CPG Products', 'Aruze Corp',
       'Gamebridge', 'Midas Interactive Entertainment', 'Jaleco',
       'Answer Software', 'XS Games', 'Activision Blizzard',
       'Pack In Soft', 'Xplosiv', 'Ultravision', 'GameMill Entertainment',
       'Wanadoo', 'NovaLogic', 'Epoch', 'BAM! Entertainment',
       'Knowledge Adventure', 'Mastiff', 'Tetris Online',
       'Harmonix Music Systems', 'ESP', 'TYO', 'Telegames',
       'Mud Duck Productions', 'Screenlife', 'Pioneer LDC', 'Zoo Games',
       'Magical Company', 'Mentor Interactive', 'Kemco',
       'Human Entertainment', 'Avanquest', 'Data Age',
       'Electronic Arts Victor', 'Black Bean Games', 'Jack of All Games',
       '989 Sports', 'Takara Tomy', 'Media Rings', 'Elf', 'Kalypso Media',
       'Starfish', 'Zushi Games', 'Jorudan', 'Destination Software, Inc',
       'New', 'Brash Entertainment', 'ITT Family Games', 'PopCap Games',
       'Home Entertainment Suppliers', 'Ackkstudios', 'Parker Bros.',
       'Starpath Corp.', 'P2 Games', 'BPS', 'Gathering of Developers',
       'NewKidCo', 'Storm City Games', 'CokeM Interactive',
       'CBS Electronics', 'Magix', 'Marvelous Interactive',
       'Nihon Falcom Corporation', 'Wargaming.net', 'Angel Studios',
       'Arc System Works', 'Playmates', 'SNK Playmore',
       'Hamster Corporation', 'From Software', 'Nippon Columbia',
       'Nichibutsu', 'Little Orbit', 'Conspiracy Entertainment',
       'DTP Entertainment', 'Hect', 'Mumbo Jumbo',
       'Pacific Century Cyber Works', 'Indie Games', 'NEC', 'Axela',
       'ArtDink', 'Sunsoft', 'Gust', 'SNK', 'NEC Interchannel', 'FuRyu',
       'Xing Entertainment', 'ValuSoft', 'Telltale Games',
       'Victor Interactive', 'Detn8 Games', 'American Softworks',
       'Nordcurrent', 'Bomb', 'Falcom Corporation', 'AQ Interactive',
       'CCP', 'Milestone S.r.l.', 'Sears', 'JoWood Productions',
       'Seta Corporation', 'On Demand', 'NCS', 'Aspyr',
       'Gremlin Interactive Ltd', 'Agatsuma Entertainment',
       'Compile Heart', 'Culture Brain', 'Mad Catz', 'Shogakukan',
       'Merscom LLC', 'Rebellion Developments', 'Nippon Telenet',
       'TDK Core', 'bitComposer Games', 'Foreign Media Games', 'Astragon',
       'SSI', 'Kadokawa Games', 'Idea Factory',
       'Performance Designed Products', 'Asylum Entertainment',
       'Core Design Ltd.', 'PlayV', 'UFO Interactive',
       'Idea Factory International', 'Playlogic Game Factory',
       'Essential Games', 'Adeline Software', 'Funcom',
       'Panther Software', 'Blast! Entertainment Ltd', 'Game Life',
       'DSI Games', 'Avalon Interactive', 'Popcorn Arcade',
       'Neko Entertainment', 'Vir2L Studios', 'Aques', 'Success',
       'Syscom', 'White Park Bay Software', 'System 3',
       'Vatical Entertainment', 'Daedalic', 'Media Factory', 'Vic Tokai',
       'The Adventure Company', 'Game Arts', 'Broccoli', 'Acquire',
       'General Entertainment', 'Excalibur Publishing', 'Imadio',
       'Swing! Entertainment', 'Sony Music Entertainment', 'Aqua Plus',
       'Paradox Interactive', 'Hip Interactive',
       'DreamCatcher Interactive', 'Tripwire Interactive', 'Sting',
       'Yacht Club Games', 'SCS Software', 'Bigben Interactive',
       'Havas Interactive', 'Slitherine Software', 'Funsta', 'Telstar',
       'U.S. Gold', 'DreamWorks Interactive', 'Data Design Interactive',
       'MTO', 'DHM Interactive', 'FunSoft', 'SPS', 'Bohemia Interactive',
       'Tru Blu Entertainment', 'Moss', 'T&E Soft', 'O-Games',
       'Aksys Games', 'NDA Productions', 'Data East',
       'Time Warner Interactive', 'Gainax Network Systems', 'Daito',
       'O3 Entertainment', 'Gameloft', 'Xicat Interactive',
       'Simon & Schuster Interactive', 'Valcon Games', 'PopTop Software',
       'TOHO', 'HMH Interactive', '5pb', 'Cave',
       'CDV Software Entertainment', 'PM Studios', 'Paon', 'Micro Cabin',
       'Benesse', 'Type-Moon', 'Enjoy Gaming ltd.', 'Asmik Corp',
       'Interplay Productions', 'Asmik Ace Entertainment', 'Image Epoch',
       'Phantom EFX', 'Evolved Games', 'responDESIGN',
       'Culture Publishers', 'Hackberry', 'Hearty Robin', 'Nippon Amuse',
       'Origin Systems', 'Seventh Chord', 'Mitsui', 'Milestone',
       'Flight-Plan', 'Glams', 'Reef Entertainment', 'Locus', 'Warp',
       'Microids', 'Daedalic Entertainment', 'Alternative Software',
       'Myelin Media', 'Mercury Games', 'Irem Software Engineering',
       'Graffiti', 'Sunrise Interactive', 'Elite', 'Evolution Games',
       'Tivola', 'Global A Entertainment', 'Edia', 'Athena', 'Aria',
       'Gamecock', 'Tommo', 'Altron', 'Happinet', 'iWin', 'Media Works',
       'Fortyfive', 'Revolution Software', 'Imax', 'Crimson Cow',
       '10TACLE Studios', 'Groove Games', 'Pack-In-Video',
       'Insomniac Games', 'Asgard', 'Ecole', 'Yumedia', 'Phenomedia',
       'HAL Laboratory', 'Grand Prix Games', 'DigiCube', 'Creative Core',
       'Kaga Create', 'WayForward Technologies', 'LSP Games',
       'ASCII Media Works', 'Coconuts Japan', 'Arika', 'Ertain',
       'Marvel Entertainment', 'Prototype', 'TopWare Interactive',
       'Phantagram', '1C Company', 'The Learning Company', 'TechnoSoft',
       'Vap', 'Misawa', 'Tradewest', 'Team17 Software', 'Yeti', 'Pow',
       'Navarre Corp', 'MediaQuest', 'Max Five', 'Comfort',
       'Monte Christo Multimedia', 'Pony Canyon', 'Riverhillsoft',
       'Summitsoft', 'Milestone S.r.l', 'Playmore', 'MLB.com',
       'Kool Kizz', 'Flashpoint Games', '49Games',
       'Ascaron Entertainment GmbH', 'Alawar Entertainment', 'CyberFront',
       'Cloud Imperium Games Corporation', 'Societa',
       'Virtual Play Games', 'Interchannel', 'Sonnet', 'Experience Inc.',
       'Zenrin', 'Iceberg Interactive', 'Ivolgamus', '2D Boy',
       'Kando Games', 'Office Create', 'Mamba Games', 'Fields',
       'Princess Soft', 'Maximum Family Games', 'Berkeley', 'Fuji',
       'Dusenberry Martin Racing', 'imageepoch Inc.', 'Big Fish Games',
       'Her Interactive', 'Kamui', 'ASK', 'Headup Games', 'KSS',
       'Cygames', 'KID', 'Quinrose', 'Sunflowers', 'dramatic create',
       'TGL', 'Encore', 'Extreme Entertainment Group', 'Intergrow',
       'G.Rev', 'Sweets', 'Kokopeli Digital Studios', 'Number None',
       'Nexon', 'BushiRoad', 'Tryfirst', 'Strategy First', '7G//AMES',
       'GN Software', "Yuke's", 'Easy Interactive', 'FuRyu Corporation',
       'Lexicon Entertainment', 'Paon Corporation', 'Kids Station', 'GOA',
       'Licensed 4U', 'Graphsim Entertainment', 'King Records',
       'Introversion Software', 'Minato Station', 'Blue Byte', 'Gaga',
       'Yamasa Entertainment', 'Plenty', 'Views', 'fonfun', 'NetRevo',
       'Codemasters Online', 'Quintet', 'Phoenix Games', 'Dorart',
       'Marvelous Games', 'Focus Multimedia', 'Imageworks',
       'Karin Entertainment', 'Aerosoft', 'Devolver Digital',
       'Technos Japan Corporation', 'Gakken', 'Mirai Shounen',
       'Datam Polystar', 'Saurus', 'HuneX', 'Revolution (Japan)',
       'Giza10', 'Visco', 'Alvion', 'Mycom', 'Giga', 'Warashi',
       'System Soft', 'Sold Out', 'Lighthouse Interactive',
       'Masque Publishing', 'RED Entertainment', 'Michaelsoft',
       'Media Entertainment', 'New World Computing', 'Genterprise',
       'Interworks Unlimited, Inc.', 'Boost On', 'Stainless Games',
       'EON Digital Entertainment', 'Epic Games', 'Naxat Soft',
       'Ascaron Entertainment', 'Piacci', 'Liquid Games',
       'Paradox Development', 'Otomate', 'Ongakukan', 'Commseed',
       'Inti Creates', 'Takuyo', 'Interchannel-Holon', 'Nitroplus',
       'Rain Games', 'UIG Entertainment'], dtype=object)

In [34]:
df['Publisher'] = df['Publisher'].str.replace('5', 'Five')
df['Publisher'] = df['Publisher'].str.replace('9', 'Nine')
df['Publisher'] = df['Publisher'].str.replace('8', 'Eight')
df['Publisher'] = df['Publisher'].str.replace('3', 'Three')
df['Publisher'] = df['Publisher'].str.replace('2', 'Tow')
df['Publisher'] = df['Publisher'].str.replace('7', 'Seven')
df['Publisher'] = df['Publisher'].str.replace('6', 'Six')
df['Publisher'] = df['Publisher'].str.replace('4', 'Four')
df['Publisher'] = df['Publisher'].str.replace('1', 'One')
df['Publisher'] = df['Publisher'].str.replace('0', 'Zero')

In [35]:
df['Publisher'] = df['Publisher'].replace('[^a-zA-Z0-9\s]', '', regex=True)

In [36]:
df['Publisher'].unique()

array(['Nintendo', 'Microsoft Game Studios', 'TakeTwo Interactive',
       'Sony Computer Entertainment', 'Activision', 'Ubisoft',
       'Bethesda Softworks', 'Electronic Arts', 'Sega', 'SquareSoft',
       'Atari', 'FiveZeroFive Games', 'Capcom', 'GT Interactive',
       'Konami Digital Entertainment',
       'Sony Computer Entertainment Europe', 'Square Enix', 'LucasArts',
       'Virgin Interactive', 'Warner Bros Interactive Entertainment',
       'Universal Interactive', 'Eidos Interactive', 'RedOctane',
       'Vivendi Games', 'Enix Corporation', 'Namco Bandai Games',
       'Palcom', 'Hasbro Interactive', 'THQ', 'Fox Interactive',
       'Acclaim Entertainment', 'MTV Games', 'Disney Interactive Studios',
       'Unknown', 'Majesco Entertainment', 'Codemasters', 'Red Orb',
       'Level Five', 'Midway Games', 'JVC', 'Deep Silver',
       'NineEightNine Studios', 'NCSoft', 'UEP Systems', 'Maxis',
       'Imagic', 'Tecmo Koei', 'Valve Software', 'ASCII Entertainment',
       'Mindscape', 'Infogrames', 'Arena Entertainment', 'Square',
       'Activision Value', 'Banpresto', 'DThreePublisher',
       'Oxygen Interactive', 'Red Storm Entertainment', 'Video System',
       'Hello Games', 'Global Star', 'Gotham Games', 'Westwood Studios',
       'GungHo', 'Crave Entertainment', 'Hudson Soft',
       'Rising Star Games', 'Atlus', 'TDK Mediactive', 'ASC Games',
       'Accolade', 'Sony Online Entertainment', 'ThreeDO', 'RTL',
       'Natsume', 'Focus Home Interactive', 'Alchemist',
       'Black Label Games', 'SouthPeak Games', 'Mastertronic', 'Ocean',
       'Zoo Digital Publishing', 'Psygnosis', 'City Interactive',
       'Empire Interactive', 'Compile', 'Russel', 'Taito', 'Agetec',
       'GSP', 'Microprose', 'Play It', 'Slightly Mad Studios',
       'Tomy Corporation', 'Sammy Corporation', 'Koch Media',
       'Game Factory', 'Titus', 'Marvelous Entertainment', 'Genki',
       'Mojang', 'Pinnacle', 'CTO SpA', 'TalonSoft', 'Crystal Dynamics',
       'Quelle', 'mixi Inc', 'Rage Software', 'Ubisoft Annecy',
       'Scholastic Inc', 'Interplay', 'Mystique', 'ChunSoft', 'Square EA',
       'TowZeroth Century Fox Video Games', 'Avanquest Software',
       'Hudson Entertainment', 'Nordic Games', 'MenAVision', 'Nobilis',
       'SCi', 'Big Ben Interactive', 'Touchstone', 'Spike',
       'Jester Interactive', 'Nippon Ichi Software', 'LEGO Media',
       'Quest', 'Illusion Softworks', 'Tigervision', 'Funbox Media',
       'Rocket Company', 'Metro ThreeD', 'Mattel Interactive',
       'IE Institute', 'Rondomedia',
       'Sony Computer Entertainment America', 'Universal Gamex',
       'Ghostlight', 'Wizard Video Games', 'Coleco',
       'BMG Interactive Entertainment', 'PQube', 'Trion Worlds', 'Laguna',
       'Ignition Entertainment', 'Takara', 'Kadokawa Shoten', 'Destineer',
       'Enterbrain', 'Xseed Games', 'Imagineer',
       'System Three Arcade Software', 'CPG Products', 'Aruze Corp',
       'Gamebridge', 'Midas Interactive Entertainment', 'Jaleco',
       'Answer Software', 'XS Games', 'Activision Blizzard',
       'Pack In Soft', 'Xplosiv', 'Ultravision', 'GameMill Entertainment',
       'Wanadoo', 'NovaLogic', 'Epoch', 'BAM Entertainment',
       'Knowledge Adventure', 'Mastiff', 'Tetris Online',
       'Harmonix Music Systems', 'ESP', 'TYO', 'Telegames',
       'Mud Duck Productions', 'Screenlife', 'Pioneer LDC', 'Zoo Games',
       'Magical Company', 'Mentor Interactive', 'Kemco',
       'Human Entertainment', 'Avanquest', 'Data Age',
       'Electronic Arts Victor', 'Black Bean Games', 'Jack of All Games',
       'NineEightNine Sports', 'Takara Tomy', 'Media Rings', 'Elf',
       'Kalypso Media', 'Starfish', 'Zushi Games', 'Jorudan',
       'Destination Software Inc', 'New', 'Brash Entertainment',
       'ITT Family Games', 'PopCap Games', 'Home Entertainment Suppliers',
       'Ackkstudios', 'Parker Bros', 'Starpath Corp', 'PTow Games', 'BPS',
       'Gathering of Developers', 'NewKidCo', 'Storm City Games',
       'CokeM Interactive', 'CBS Electronics', 'Magix',
       'Marvelous Interactive', 'Nihon Falcom Corporation',
       'Wargamingnet', 'Angel Studios', 'Arc System Works', 'Playmates',
       'SNK Playmore', 'Hamster Corporation', 'From Software',
       'Nippon Columbia', 'Nichibutsu', 'Little Orbit',
       'Conspiracy Entertainment', 'DTP Entertainment', 'Hect',
       'Mumbo Jumbo', 'Pacific Century Cyber Works', 'Indie Games', 'NEC',
       'Axela', 'ArtDink', 'Sunsoft', 'Gust', 'SNK', 'NEC Interchannel',
       'FuRyu', 'Xing Entertainment', 'ValuSoft', 'Telltale Games',
       'Victor Interactive', 'DetnEight Games', 'American Softworks',
       'Nordcurrent', 'Bomb', 'Falcom Corporation', 'AQ Interactive',
       'CCP', 'Milestone Srl', 'Sears', 'JoWood Productions',
       'Seta Corporation', 'On Demand', 'NCS', 'Aspyr',
       'Gremlin Interactive Ltd', 'Agatsuma Entertainment',
       'Compile Heart', 'Culture Brain', 'Mad Catz', 'Shogakukan',
       'Merscom LLC', 'Rebellion Developments', 'Nippon Telenet',
       'TDK Core', 'bitComposer Games', 'Foreign Media Games', 'Astragon',
       'SSI', 'Kadokawa Games', 'Idea Factory',
       'Performance Designed Products', 'Asylum Entertainment',
       'Core Design Ltd', 'PlayV', 'UFO Interactive',
       'Idea Factory International', 'Playlogic Game Factory',
       'Essential Games', 'Adeline Software', 'Funcom',
       'Panther Software', 'Blast Entertainment Ltd', 'Game Life',
       'DSI Games', 'Avalon Interactive', 'Popcorn Arcade',
       'Neko Entertainment', 'VirTowL Studios', 'Aques', 'Success',
       'Syscom', 'White Park Bay Software', 'System Three',
       'Vatical Entertainment', 'Daedalic', 'Media Factory', 'Vic Tokai',
       'The Adventure Company', 'Game Arts', 'Broccoli', 'Acquire',
       'General Entertainment', 'Excalibur Publishing', 'Imadio',
       'Swing Entertainment', 'Sony Music Entertainment', 'Aqua Plus',
       'Paradox Interactive', 'Hip Interactive',
       'DreamCatcher Interactive', 'Tripwire Interactive', 'Sting',
       'Yacht Club Games', 'SCS Software', 'Bigben Interactive',
       'Havas Interactive', 'Slitherine Software', 'Funsta', 'Telstar',
       'US Gold', 'DreamWorks Interactive', 'Data Design Interactive',
       'MTO', 'DHM Interactive', 'FunSoft', 'SPS', 'Bohemia Interactive',
       'Tru Blu Entertainment', 'Moss', 'TE Soft', 'OGames',
       'Aksys Games', 'NDA Productions', 'Data East',
       'Time Warner Interactive', 'Gainax Network Systems', 'Daito',
       'OThree Entertainment', 'Gameloft', 'Xicat Interactive',
       'Simon  Schuster Interactive', 'Valcon Games', 'PopTop Software',
       'TOHO', 'HMH Interactive', 'Fivepb', 'Cave',
       'CDV Software Entertainment', 'PM Studios', 'Paon', 'Micro Cabin',
       'Benesse', 'TypeMoon', 'Enjoy Gaming ltd', 'Asmik Corp',
       'Interplay Productions', 'Asmik Ace Entertainment', 'Image Epoch',
       'Phantom EFX', 'Evolved Games', 'responDESIGN',
       'Culture Publishers', 'Hackberry', 'Hearty Robin', 'Nippon Amuse',
       'Origin Systems', 'Seventh Chord', 'Mitsui', 'Milestone',
       'FlightPlan', 'Glams', 'Reef Entertainment', 'Locus', 'Warp',
       'Microids', 'Daedalic Entertainment', 'Alternative Software',
       'Myelin Media', 'Mercury Games', 'Irem Software Engineering',
       'Graffiti', 'Sunrise Interactive', 'Elite', 'Evolution Games',
       'Tivola', 'Global A Entertainment', 'Edia', 'Athena', 'Aria',
       'Gamecock', 'Tommo', 'Altron', 'Happinet', 'iWin', 'Media Works',
       'Fortyfive', 'Revolution Software', 'Imax', 'Crimson Cow',
       'OneZeroTACLE Studios', 'Groove Games', 'PackInVideo',
       'Insomniac Games', 'Asgard', 'Ecole', 'Yumedia', 'Phenomedia',
       'HAL Laboratory', 'Grand Prix Games', 'DigiCube', 'Creative Core',
       'Kaga Create', 'WayForward Technologies', 'LSP Games',
       'ASCII Media Works', 'Coconuts Japan', 'Arika', 'Ertain',
       'Marvel Entertainment', 'Prototype', 'TopWare Interactive',
       'Phantagram', 'OneC Company', 'The Learning Company', 'TechnoSoft',
       'Vap', 'Misawa', 'Tradewest', 'TeamOneSeven Software', 'Yeti',
       'Pow', 'Navarre Corp', 'MediaQuest', 'Max Five', 'Comfort',
       'Monte Christo Multimedia', 'Pony Canyon', 'Riverhillsoft',
       'Summitsoft', 'Playmore', 'MLBcom', 'Kool Kizz',
       'Flashpoint Games', 'FourNineGames', 'Ascaron Entertainment GmbH',
       'Alawar Entertainment', 'CyberFront',
       'Cloud Imperium Games Corporation', 'Societa',
       'Virtual Play Games', 'Interchannel', 'Sonnet', 'Experience Inc',
       'Zenrin', 'Iceberg Interactive', 'Ivolgamus', 'TowD Boy',
       'Kando Games', 'Office Create', 'Mamba Games', 'Fields',
       'Princess Soft', 'Maximum Family Games', 'Berkeley', 'Fuji',
       'Dusenberry Martin Racing', 'imageepoch Inc', 'Big Fish Games',
       'Her Interactive', 'Kamui', 'ASK', 'Headup Games', 'KSS',
       'Cygames', 'KID', 'Quinrose', 'Sunflowers', 'dramatic create',
       'TGL', 'Encore', 'Extreme Entertainment Group', 'Intergrow',
       'GRev', 'Sweets', 'Kokopeli Digital Studios', 'Number None',
       'Nexon', 'BushiRoad', 'Tryfirst', 'Strategy First', 'SevenGAMES',
       'GN Software', 'Yukes', 'Easy Interactive', 'FuRyu Corporation',
       'Lexicon Entertainment', 'Paon Corporation', 'Kids Station', 'GOA',
       'Licensed FourU', 'Graphsim Entertainment', 'King Records',
       'Introversion Software', 'Minato Station', 'Blue Byte', 'Gaga',
       'Yamasa Entertainment', 'Plenty', 'Views', 'fonfun', 'NetRevo',
       'Codemasters Online', 'Quintet', 'Phoenix Games', 'Dorart',
       'Marvelous Games', 'Focus Multimedia', 'Imageworks',
       'Karin Entertainment', 'Aerosoft', 'Devolver Digital',
       'Technos Japan Corporation', 'Gakken', 'Mirai Shounen',
       'Datam Polystar', 'Saurus', 'HuneX', 'Revolution Japan',
       'GizaOneZero', 'Visco', 'Alvion', 'Mycom', 'Giga', 'Warashi',
       'System Soft', 'Sold Out', 'Lighthouse Interactive',
       'Masque Publishing', 'RED Entertainment', 'Michaelsoft',
       'Media Entertainment', 'New World Computing', 'Genterprise',
       'Interworks Unlimited Inc', 'Boost On', 'Stainless Games',
       'EON Digital Entertainment', 'Epic Games', 'Naxat Soft',
       'Ascaron Entertainment', 'Piacci', 'Liquid Games',
       'Paradox Development', 'Otomate', 'Ongakukan', 'Commseed',
       'Inti Creates', 'Takuyo', 'InterchannelHolon', 'Nitroplus',
       'Rain Games', 'UIG Entertainment'], dtype=object)


> <div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 28px; color: #FFA500; font-weight: bold;"> Congrats !! We have Cleaned All Categorical Data</div>




---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;">2.6 || Dealing With Numerical Columns</div>

---

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>

Index: 11470 entries, 0 to 16596

Data columns (total 11 columns):

 #   Column        Non-Null Count  Dtype

---  ------        --------------  -----

 0   Rank          11470 non-null  int64

 1   Name          11470 non-null  object

 2   Platform      11470 non-null  object

 3   Year          11470 non-null  int64

 4   Genre         11470 non-null  object

 5   Publisher     11470 non-null  object

 6   NA_Sales      11470 non-null  float64

 7   EU_Sales      11470 non-null  float64

 8   JP_Sales      11470 non-null  float64

 9   Other_Sales   11470 non-null  float64

 10  Global_Sales  11470 non-null  float64

dtypes: float64(5), int64(2), object(4)

memory usage: 1.1+ MB

In [38]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon RedPokemon Blue,GB,1996,Role Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

<div style="border: 3px solid orange; border-radius: 20px; padding: 10px; width: fit-content;">
    <div style="background: linear-gradient(45deg, #FFFFFF, #FFDAB9); border-radius: 20px; padding: 30px; font-family: Arial, sans-serif; font-size: 28px; color: #FFA500; display: inline-block; text-align: center; box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);">
        <span style="font-weight: bold; margin-right: 10px;">3</span>
        <span style="color: #FF6347; margin-right: 10px; font-size: 42px;">🌠</span>
        <span style="font-style: roboto; font-weight: bold;">Deep Dive
    </div>
</div>

> <div style="margin-top: 12px; font-family: Arial, sans-serif; font-size: 17px; color: #FFA500; font-weight: bold;">Sales are paramount in every market, serving as a crucial metric for assessing performance and guiding strategic decisions. Therefore, our forthcoming analysis will focus primarily on the sales data of the top 15 performers over the past five years.</div>

***Total fractional sales***:
- Well the sales are in miilions so lets take a look :)

In [39]:
df['Year'].max()

2020

In [40]:
!pip install tabulate

Requirement already satisfied: tabulate in /opt/conda/lib/python3.10/site-packages (0.9.0)




---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;"> 3.1 || Top 10 Worldwide Sales Games</div>

---

In [41]:
# Filter the DataFrame for years between 2015 and 2020
filtered_df = df[(df['Year'] >= 2015) & (df['Year'] <= 2020)]

# Group by 'Year', 'Name', 'Platform', 'Genre', and 'Publisher', and sum the 'Global_Sales'
top_10_games_global_sales = filtered_df.groupby(['Year', 'Name', 'Platform', 'Genre', 'Publisher'])['Global_Sales'].sum().nlargest(15)
top_10_games_global_sales

Year  Name                                   Platform  Genre         Publisher
2015  Call of Duty Black Ops Three           PSFour    Shooter       Activision                               14.24
      FIFA OneSix                            PSFour    Sports        Electronic Arts                           8.49
      Star Wars Battlefront TwoZeroOneFive   PSFour    Shooter       Electronic Arts                           7.67
      Fallout Four                           PSFour    Role Playing  Bethesda Softworks                        6.96
2016  FIFA OneSeven                          PSFour    Sports        Electronic Arts                           4.77
2015  Splatoon                               WiiU      Shooter       Nintendo                                  4.57
      Uncharted The Nathan Drake Collection  PSFour    Action        Sony Computer Entertainment               4.47
      Halo Five Guardians                    XOne      Shooter       Microsoft Game Studios                    4.26
2016  Uncharted Four A Thiefs End            PSFour    Shooter       Sony Computer Entertainment               4.20
2015  NBA TwoKOneSix                         PSFour    Sports        TakeTwo Interactive                       3.85
      Batman Arkham Knight                   PSFour    Action        Warner Bros Interactive Entertainment     3.79
      The Witcher Three Wild Hunt            PSFour    Role Playing  Namco Bandai Games                        3.73
2016  Tom Clancys The Division               PSFour    Shooter       Ubisoft                                   3.61
2015  Metal Gear Solid V The Phantom Pain    PSFour    Action        Konami Digital Entertainment              3.38
      Assassins Creed Syndicate              PSFour    Action        Ubisoft                                   3.28
Name: Global_Sales, dtype: float64

|    |   Year | Name                                   | Platform   | Genre        | Publisher                             |   Global_Sales |
|----|--------|----------------------------------------|------------|--------------|---------------------------------------|----------------|
|  0 |   2015 | Call of Duty Black Ops Three           | PSFour     | Shooter      | Activision                            |          14.24 |
|  1 |   2015 | FIFA OneSix                            | PSFour     | Sports       | Electronic Arts                       |           8.49 |
|  2 |   2015 | Star Wars Battlefront TwoZeroOneFive   | PSFour     | Shooter      | Electronic Arts                       |           7.67 |
|  3 |   2015 | Fallout Four                           | PSFour     | Role Playing | Bethesda Softworks                    |           6.96 |
|  4 |   2016 | FIFA OneSeven                          | PSFour     | Sports       | Electronic Arts                       |           4.77 |
|  5 |   2015 | Splatoon                               | WiiU       | Shooter      | Nintendo                              |           4.57 |
|  6 |   2015 | Uncharted The Nathan Drake Collection  | PSFour     | Action       | Sony Computer Entertainment           |           4.47 |
|  7 |   2015 | Halo Five Guardians                    | XOne       | Shooter      | Microsoft Game Studios                |           4.26 |
|  8 |   2016 | Uncharted Four A Thiefs End            | PSFour     | Shooter      | Sony Computer Entertainment           |           4.20 |
|  9 |   2015 | NBA TwoKOneSix                         | PSFour     | Sports       | TakeTwo Interactive                   |           3.85 |
| 10 |   2015 | Batman Arkham Knight                   | PSFour     | Action       | Warner Bros Interactive Entertainment |           3.79 |
| 11 |   2015 | The Witcher Three Wild Hunt            | PSFour     | Role Playing | Namco Bandai Games                    |           3.73 |
| 12 |   2016 | Tom Clancys The Division               | PSFour     | Shooter      | Ubisoft                               |           3.61 |
| 13 |   2015 | Metal Gear Solid V The Phantom Pain    | PSFour     | Action       | Konami Digital Entertainment          |           3.38 |
| 14 |   2015 | Assassins Creed Syndicate              | PSFour     | Action       | Ubisoft                               |           3.28 |




---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;"> 3.2 || Top 10 Sales Games in North America </div>

---

In [43]:
# Filter the DataFrame for years between 2015 and 2020
filtered_df = df[(df['Year'] >= 2015) & (df['Year'] <= 2020)]

# Group by 'Year', 'Name', 'Platform', 'Genre', and 'Publisher', and sum the 'Global_Sales'
top_10_games_North_America_sales = filtered_df.groupby(['Year', 'Name', 'Platform', 'Genre', 'Publisher'])['NA_Sales'].sum().nlargest(15)
top_10_games_North_America_sales

Year  Name                                     Platform  Genre         Publisher
2015  Call of Duty Black Ops Three             PSFour    Shooter       Activision                               5.77
      Star Wars Battlefront TwoZeroOneFive     PSFour    Shooter       Electronic Arts                          2.93
      Halo Five Guardians                      XOne      Shooter       Microsoft Game Studios                   2.64
      NBA TwoKOneSix                           PSFour    Sports        TakeTwo Interactive                      2.48
      Fallout Four                             PSFour    Role Playing  Bethesda Softworks                       2.47
      Gears of War Ultimate Edition            XOne      Shooter       Microsoft Game Studios                   2.38
      Madden NFL OneSix                        PSFour    Sports        Electronic Arts                          2.33
      Uncharted The Nathan Drake Collection    PSFour    Action        Sony Computer Entertainment              1.96
      Splatoon                                 WiiU      Shooter       Nintendo                                 1.55
      Batman Arkham Knight                     PSFour    Action        Warner Bros Interactive Entertainment    1.49
      Mortal Kombat X                          PSFour    Fighting      Warner Bros Interactive Entertainment    1.47
2016  Uncharted Four A Thiefs End              PSFour    Shooter       Sony Computer Entertainment              1.30
      Tom Clancys The Division                 PSFour    Shooter       Ubisoft                                  1.28
2015  Super Mario Maker                        WiiU      Platform      Nintendo                                 1.18
      The Legend of Zelda Majoras Mask ThreeD  ThreeDS   Action        Nintendo                                 1.14
Name: NA_Sales, dtype: float64

|    |   Year | Name                                      | Platform   | Genre      | Publisher                             |   NA_Sales |
|----|--------|-------------------------------------------|------------|------------|---------------------------------------|------------|
|  0 |   2015 | Call of Duty Black Ops Three              | PSFour     | Shooter    | Activision                            |       5.77 |
|  1 |   2015 | Star Wars Battlefront TwoZeroOneFive      | PSFour     | Shooter    | Electronic Arts                       |       2.93 |
|  2 |   2015 | Halo Five Guardians                       | XOne       | Shooter    | Microsoft Game Studios                |       2.64 |
|  3 |   2015 | NBA TwoKOneSix                            | PSFour     | Sports     | TakeTwo Interactive                   |       2.48 |
|  4 |   2015 | Fallout Four                              | PSFour     | Role Playing | Bethesda Softworks                  |       2.47 |
|  5 |   2015 | Gears of War Ultimate Edition             | XOne       | Shooter    | Microsoft Game Studios                |       2.38 |
|  6 |   2015 | Madden NFL OneSix                         | PSFour     | Sports     | Electronic Arts                       |       2.33 |
|  7 |   2015 | Uncharted The Nathan Drake Collection     | PSFour     | Action     | Sony Computer Entertainment           |       1.96 |
|  8 |   2015 | Splatoon                                  | WiiU       | Shooter    | Nintendo                              |       1.55 |
|  9 |   2015 | Batman Arkham Knight                      | PSFour     | Action     | Warner Bros Interactive Entertainment |       1.49 |
| 10 |   2015 | Mortal Kombat X                           | PSFour     | Fighting   | Warner Bros Interactive Entertainment |       1.47 |
| 11 |   2016 | Uncharted Four A Thiefs End               | PSFour     | Shooter    | Sony Computer Entertainment           |       1.30 |
| 12 |   2016 | Tom Clancys The Division                  | PSFour     | Shooter    | Ubisoft                               |       1.28 |
| 13 |   2015 | Super Mario Maker                         | WiiU       | Platform   | Nintendo                              |       1.18 |
| 14 |   2015 | The Legend of Zelda Majoras Mask ThreeD   | ThreeDS    | Action     | Nintendo                              |       1.14 |




---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;"> 3.3 || Top 10 Sales Games in EU</div>

---

In [45]:
# Filter the DataFrame for years between 2015 and 2020
filtered_df = df[(df['Year'] >= 2015) & (df['Year'] <= 2020)]

# Group by 'Year', 'Name', 'Platform', 'Genre', and 'Publisher', and sum the 'Global_Sales'
top_10_games_EU_sales = filtered_df.groupby(['Year', 'Name', 'Platform', 'Genre', 'Publisher'])['EU_Sales'].sum().nlargest(15)
top_10_games_EU_sales

Year  Name                                   Platform  Genre         Publisher
2015  FIFA OneSix                            PSFour    Sports        Electronic Arts                          6.06
      Call of Duty Black Ops Three           PSFour    Shooter       Activision                               5.81
2016  FIFA OneSeven                          PSFour    Sports        Electronic Arts                          3.75
2015  Star Wars Battlefront TwoZeroOneFive   PSFour    Shooter       Electronic Arts                          3.29
      Fallout Four                           PSFour    Role Playing  Bethesda Softworks                       3.15
2016  Uncharted Four A Thiefs End            PSFour    Shooter       Sony Computer Entertainment              2.07
2015  The Witcher Three Wild Hunt            PSFour    Role Playing  Namco Bandai Games                       2.00
      Assassins Creed Syndicate              PSFour    Action        Ubisoft                                  1.92
      Uncharted The Nathan Drake Collection  PSFour    Action        Sony Computer Entertainment              1.69
2016  Tom Clancys The Division               PSFour    Shooter       Ubisoft                                  1.61
2015  Batman Arkham Knight                   PSFour    Action        Warner Bros Interactive Entertainment    1.58
      Need for Speed TwoZeroOneFive          PSFour    Racing        Electronic Arts                          1.49
      Metal Gear Solid V The Phantom Pain    PSFour    Action        Konami Digital Entertainment             1.35
      Halo Five Guardians                    XOne      Shooter       Microsoft Game Studios                   1.20
      Tom Clancys Rainbow Six Siege          PSFour    Shooter       Ubisoft                                  1.16
Name: EU_Sales, dtype: float64

|    |   Year | Name                                   | Platform   | Genre         | Publisher                             |   EU_Sales |
|----|--------|----------------------------------------|------------|---------------|---------------------------------------|------------|
|  0 |   2015 | FIFA OneSix                            | PSFour     | Sports        | Electronic Arts                       |       6.06 |
|  1 |   2015 | Call of Duty Black Ops Three           | PSFour     | Shooter       | Activision                            |       5.81 |
|  2 |   2016 | FIFA OneSeven                          | PSFour     | Sports        | Electronic Arts                       |       3.75 |
|  3 |   2015 | Star Wars Battlefront TwoZeroOneFive   | PSFour     | Shooter       | Electronic Arts                       |       3.29 |
|  4 |   2015 | Fallout Four                           | PSFour     | Role Playing  | Bethesda Softworks                    |       3.15 |
|  5 |   2016 | Uncharted Four A Thiefs End            | PSFour     | Shooter       | Sony Computer Entertainment           |       2.07 |
|  6 |   2015 | The Witcher Three Wild Hunt            | PSFour     | Role Playing  | Namco Bandai Games                    |       2.00 |
|  7 |   2015 | Assassins Creed Syndicate              | PSFour     | Action        | Ubisoft                               |       1.92 |
|  8 |   2015 | Uncharted The Nathan Drake Collection | PSFour     | Action        | Sony Computer Entertainment           |       1.69 |
|  9 |   2016 | Tom Clancys The Division               | PSFour     | Shooter       | Ubisoft                               |       1.61 |
| 10 |   2015 | Batman Arkham Knight                   | PSFour     | Action        | Warner Bros Interactive Entertainment |       1.58 |
| 11 |   2015 | Need for Speed TwoZeroOneFive         | PSFour     | Racing        | Electronic Arts                       |       1.49 |
| 12 |   2015 | Metal Gear Solid V The Phantom Pain   | PSFour     | Action        | Konami Digital Entertainment          |       1.35 |
| 13 |   2015 | Halo Five Guardians                   | XOne       | Shooter       | Microsoft Game Studios                |       1.20 |
| 14 |   2015 | Tom Clancys Rainbow Six Siege         | PSFour     | Shooter       | Ubisoft                               |       1.16 |




---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;"> 3.4 || Top 10  Sales Games in Japan </div>

---

In [47]:
# Filter the DataFrame for years between 2015 and 2020
filtered_df = df[(df['Year'] >= 2015) & (df['Year'] <= 2020)]

# Group by 'Year', 'Name', 'Platform', 'Genre', and 'Publisher', and sum the 'Global_Sales'
top_10_games_JP_sales = filtered_df.groupby(['Year', 'Name', 'Platform', 'Genre', 'Publisher'])['JP_Sales'].sum().nlargest(15)
top_10_games_JP_sales

Year  Name                                     Platform  Genre         Publisher
2015  Monster Hunter X                         ThreeDS   Action        Capcom                          2.78
      Yokai Watch Busters                      ThreeDS   Action        Level Five                      2.28
      Splatoon                                 WiiU      Shooter       Nintendo                        1.44
      Animal Crossing Happy Home Designer      ThreeDS   Simulation    Nintendo                        1.39
2016  Yokai Watch Three                        ThreeDS   Action        Level Five                      1.27
2015  Super Mario Maker                        WiiU      Platform      Nintendo                        0.93
      Monster Strike ThreeDS                   ThreeDS   Action        mixi Inc                        0.86
      Rhythm Heaven The Best                   ThreeDS   Misc          Nintendo                        0.71
2016  Dragon Quest Monsters Joker Three        ThreeDS   Role Playing  Square Enix                     0.63
      Yokai Sangokushi                         ThreeDS   Action        Level Five                      0.55
2015  Fire Emblem Fates                        ThreeDS   Role Playing  Nintendo                        0.52
      Metal Gear Solid V The Phantom Pain      PSFour    Action        Konami Digital Entertainment    0.48
      The Legend of Zelda Majoras Mask ThreeD  ThreeDS   Action        Nintendo                        0.47
2016  Kirby Planet Robobot                     ThreeDS   Action        Nintendo                        0.44
2015  Tales of Zestiria                        PSThree   Role Playing  Namco Bandai Games              0.42
Name: JP_Sales, dtype: float64

|    |   Year | Name                                     | Platform   | Genre        | Publisher                          |   JP_Sales |
|----|--------|------------------------------------------|------------|--------------|------------------------------------|------------|
|  0 |   2015 | Monster Hunter X                         | ThreeDS    | Action       | Capcom                             |       2.78 |
|  1 |   2015 | Yokai Watch Busters                      | ThreeDS    | Action       | Level Five                         |       2.28 |
|  2 |   2015 | Splatoon                                 | WiiU       | Shooter      | Nintendo                           |       1.44 |
|  3 |   2015 | Animal Crossing Happy Home Designer      | ThreeDS    | Simulation   | Nintendo                           |       1.39 |
|  4 |   2016 | Yokai Watch Three                        | ThreeDS    | Action       | Level Five                         |       1.27 |
|  5 |   2015 | Super Mario Maker                        | WiiU       | Platform     | Nintendo                           |       0.93 |
|  6 |   2015 | Monster Strike                           | ThreeDS    | Action       | mixi Inc                           |       0.86 |
|  7 |   2015 | Rhythm Heaven The Best                   | ThreeDS    | Misc         | Nintendo                           |       0.71 |
|  8 |   2016 | Dragon Quest Monsters Joker Three        | ThreeDS    | Role Playing | Square Enix                        |       0.63 |
|  9 |   2016 | Yokai Sangokushi                         | ThreeDS    | Action       | Level Five                         |       0.55 |
| 10 |   2015 | Fire Emblem Fates                        | ThreeDS    | Role Playing | Nintendo                           |       0.52 |
| 11 |   2015 | Metal Gear Solid V The Phantom Pain      | PSFour     | Action       | Konami Digital Entertainment       |       0.48 |
| 12 |   2015 | The Legend of Zelda Majoras Mask ThreeD  | ThreeDS    | Action       | Nintendo                           |       0.47 |
| 13 |   2016 | Kirby Planet Robobot                     | ThreeDS    | Action       | Nintendo                           |       0.44 |
| 14 |   2015 | Tales of Zestiria                        | PSThree    | Role Playing | Namco Bandai Games                 |       0.42 |




---
<div style="margin-top: 20px; font-family: Arial, sans-serif; font-size: 22px; color: #FFA500; font-weight: bold;"> 3.5 || Top 10 Sales Gamesin other Domains </div>

---

In [49]:
# Filter the DataFrame for years between 2015 and 2020
filtered_df = df[(df['Year'] >= 2015) & (df['Year'] <= 2020)]

# Group by 'Year', 'Name', 'Platform', 'Genre', and 'Publisher', and sum the 'Global_Sales'
top_10_games_other_sales = filtered_df.groupby(['Year', 'Name', 'Platform', 'Genre', 'Publisher'])['Other_Sales'].sum().nlargest(15)
top_10_games_other_sales

Year  Name                                   Platform  Genre         Publisher
2015  Call of Duty Black Ops Three           PSFour    Shooter       Activision                               2.31
      FIFA OneSix                            PSFour    Sports        Electronic Arts                          1.26
      Star Wars Battlefront TwoZeroOneFive   PSFour    Shooter       Electronic Arts                          1.23
      Fallout Four                           PSFour    Role Playing  Bethesda Softworks                       1.10
      Uncharted The Nathan Drake Collection  PSFour    Action        Sony Computer Entertainment              0.74
      NBA TwoKOneSix                         PSFour    Sports        TakeTwo Interactive                      0.69
2016  FIFA OneSeven                          PSFour    Sports        Electronic Arts                          0.69
      Uncharted Four A Thiefs End            PSFour    Shooter       Sony Computer Entertainment              0.65
2015  Batman Arkham Knight                   PSFour    Action        Warner Bros Interactive Entertainment    0.61
      Madden NFL OneSix                      PSFour    Sports        Electronic Arts                          0.59
2016  Tom Clancys The Division               PSFour    Shooter       Ubisoft                                  0.57
2015  The Witcher Three Wild Hunt            PSFour    Role Playing  Namco Bandai Games                       0.56
      Assassins Creed Syndicate              PSFour    Action        Ubisoft                                  0.50
      Metal Gear Solid V The Phantom Pain    PSFour    Action        Konami Digital Entertainment             0.47
      Mortal Kombat X                        PSFour    Fighting      Warner Bros Interactive Entertainment    0.47
Name: Other_Sales, dtype: float64

|    |   Year | Name                                    | Platform   | Genre        | Publisher                             |   Other_Sales |
|----|--------|-----------------------------------------|------------|--------------|---------------------------------------|---------------|
|  0 |   2015 | Call of Duty Black Ops Three            | PSFour     | Shooter      | Activision                            |          2.31 |
|  1 |   2015 | FIFA OneSix                            | PSFour     | Sports       | Electronic Arts                       |          1.26 |
|  2 |   2015 | Star Wars Battlefront TwoZeroOneFive   | PSFour     | Shooter      | Electronic Arts                       |          1.23 |
|  3 |   2015 | Fallout Four                           | PSFour     | Role Playing | Bethesda Softworks                    |          1.1  |
|  4 |   2015 | Uncharted The Nathan Drake Collection   | PSFour     | Action       | Sony Computer Entertainment           |          0.74 |
|  5 |   2015 | NBA TwoKOneSix                         | PSFour     | Sports       | TakeTwo Interactive                   |          0.69 |
|  6 |   2016 | FIFA OneSeven                          | PSFour     | Sports       | Electronic Arts                       |          0.69 |
|  7 |   2016 | Uncharted Four A Thiefs End            | PSFour     | Shooter      | Sony Computer Entertainment           |          0.65 |
|  8 |   2015 | Batman Arkham Knight                   | PSFour     | Action       | Warner Bros Interactive Entertainment |          0.61 |
|  9 |   2015 | Madden NFL OneSix                      | PSFour     | Sports       | Electronic Arts                       |          0.59 |
| 10 |   2016 | Tom Clancys The Division               | PSFour     | Shooter      | Ubisoft                               |          0.57 |
| 11 |   2015 | The Witcher Three Wild Hunt            | PSFour     | Role Playing | Namco Bandai Games                    |          0.56 |
| 12 |   2015 | Assassins Creed Syndicate              | PSFour     | Action       | Ubisoft                               |          0.5  |
| 13 |   2015 | Metal Gear Solid V The Phantom Pain    | PSFour     | Action       | Konami Digital Entertainment          |          0.47 |
| 14 |   2015 | Mortal Kombat X                        | PSFour     | Fighting     | Warner Bros Interactive Entertainment |          0.47 |

---

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUuhiEqdW4njY8ecn_ps7nA1Ih6DH_PIhVA8kH5xouXA&s)